# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea1c5f22c237764a63c034772dabb8d65912c2527b9a117babd0875779ff564a964de97aae6e84ff6431b4db7f097d75766386461b9d54f0b747a394d54a3575

test:
  secret_key_base: 2d7134a5a9bcbbb7c43518974bd78ed0459e202d51be14f65b026a0a4d4120c8e6b98418d78a5d10e42459dc6cd568c17086d20d489f8550b53b690ac97fa9f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
